import { Inter } from "next/font/google";
import "./global.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} global-wrapper`}>
        <nav className="navbar">
          <Link href="/">Home</Link>
          <Link href="/username">Profile</Link>
          <Link href="/notifications">Notifications</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
